# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      #Download Spigot dependencies
      - run: mkdir ~/repo/libs
      - run: cd ~/repo
      - run: for i in "1.9" "1.9.4" "1.10.2" "1.11.2" "1.12.2" "1.13" "1.13.2"; do   echo "Downloading version $i";   wget https://funniray.com/spigot/spigot-$i.jar -O libs/spigot-$i.jar; done

      - run: openssl aes-256-cbc -d -a -in ~/repo/secring.gpg.enc -out ~/secring.gpg -k $KEY -md sha256
      #Update openssl aes-256-cbc -a -salt -in gradle.properties -out gradle.properties.enc -k $KEY -md sha256
      - run: openssl aes-256-cbc -d -a -in ~/repo/gradle.properties.enc -out ~/repo/gradle.properties -k $KEY -md sha256

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: ./gradlew shadowJar
      - run: ./gradlew githubRelease
      - run: ./gradlew --continue deploy

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: ~/repo/build/jars